export const contactNormalizerFixtures = [
  {
    id: "labeled-phone-email",
    rawText: "Customer email: Ben.Reed721@Example.com. Customer phone: 8125550134",
    expected: { email: "ben.reed721@example.com", phone: "812-555-0134" },
    expectedWarningFragments: [],
    expectedLowConfidenceFields: [],
  },
  {
    id: "unlabeled-phone-email",
    rawText: "ben.reed721@example.com remove three hickory trees 812-555-1721",
    expected: { email: "ben.reed721@example.com", phone: "812-555-1721" },
    expectedWarningFragments: [],
    expectedLowConfidenceFields: [],
  },
  {
    id: "intake-wins-over-raw",
    rawText: "Call 812-555-9999 email wrong@example.com",
    intake: { email: "RIGHT@Example.COM ", phone: "(812) 555-0134" },
    expected: { email: "right@example.com", phone: "812-555-0134" },
    expectedWarningFragments: ["multiple"],
    expectedLowConfidenceFields: [],
  },
  {
    id: "multiple-email-warning",
    rawText: "email first@example.com or second@example.com phone 8125550134",
    expected: { email: "first@example.com", phone: "812-555-0134" },
    expectedWarningFragments: ["multiple"],
    expectedLowConfidenceFields: [],
  },
  {
    id: "malformed-labeled-email",
    rawText: "Customer email: ben at example. Phone: 812-555-0134",
    expected: { email: "", phone: "812-555-0134" },
    expectedWarningFragments: [],
    expectedLowConfidenceFields: ["customer.email"],
  },
  {
    id: "malformed-labeled-phone",
    rawText: "Phone: 812-555. Email: ben@example.com",
    expected: { email: "ben@example.com", phone: "" },
    expectedWarningFragments: [],
    expectedLowConfidenceFields: ["customer.phone"],
  },
  {
    id: "price-address-no-contact",
    rawText: "3327 College Avenue remove three trees option A 1000 option B $1700",
    expected: { email: "", phone: "" },
    expectedWarningFragments: [],
    expectedLowConfidenceFields: [],
  },
  {
    id: "highway-route-no-phone",
    rawText: "Customer phone missing. Service at 777 Highway 421 Madison IN. Remove one tree 1200.",
    expected: { email: "", phone: "" },
    expectedWarningFragments: [],
    expectedLowConfidenceFields: ["customer.phone"],
  },
  {
    id: "long-id-zip-percent-no-phone",
    rawText: "Customer id 991812555013477. ZIP 47250-1234. measurement 8125550134%.",
    expected: { email: "", phone: "" },
    expectedWarningFragments: [],
    expectedLowConfidenceFields: [],
  },
  {
    id: "send-quote-email-label",
    rawText: "Send quote to Linda.Tree99@Example.org and remove oak near garage.",
    expected: { email: "linda.tree99@example.org", phone: "" },
    expectedWarningFragments: [],
    expectedLowConfidenceFields: [],
  },
  {
    id: "written-out-email",
    rawText: "Reply to mike j at gmail dot com. Cell: 812-555-0101",
    expected: { email: "mike.j@gmail.com", phone: "812-555-0101" },
    expectedWarningFragments: [],
    expectedLowConfidenceFields: [],
  },
  {
    id: "cell-label-phone",
    rawText: "Cell: +1 812 555 0198. remove maple.",
    expected: { email: "", phone: "812-555-0198" },
    expectedWarningFragments: [],
    expectedLowConfidenceFields: [],
  },
  {
    id: "phone-price-percent-guards",
    rawText: "$8125550134 is a bad price note. 8125550134% is a bad percentage note.",
    expected: { email: "", phone: "" },
    expectedWarningFragments: [],
    expectedLowConfidenceFields: [],
  },
];
