import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { existsSync } from "node:fs";

const pageSource = readFileSync("app/page.js", "utf8");
const inputFormSource = readFileSync("app/components/InputForm.jsx", "utf8");
const pdfGeneratorSource = readFileSync("app/components/PdfGenerator.jsx", "utf8");
const submissionButtonsSource = readFileSync("app/components/SubmissionButtons.jsx", "utf8");
const cssSource = readFileSync("app/styles/globals.css", "utf8");
const globalCssSource = readFileSync("styles-globals.css", "utf8");
const customerRouteSource = readFileSync("app/e/[estimateId]/EstimateClient.jsx", "utf8");
const openaiRouteSource = readFileSync("app/api/openai/route.js", "utf8");
const openaiPromptSource = readFileSync("lib/openaiPrompt.js", "utf8");
const debugPipelineSource = readFileSync("lib/debugPipeline.js", "utf8");
const jsonReviewSource = readFileSync("app/components/JsonReview.jsx", "utf8");
const reviewOverridesSource = readFileSync("lib/reviewOverrides.js", "utf8");

test("normal UI does not render raw AlphaJSON debug panel", () => {
  assert.doesNotMatch(pageSource, /<h2>AlphaJSON<\/h2>/);
  assert.doesNotMatch(pageSource, /JSON\.stringify\(alphaJson/);
});

test("Edit Notes focuses the textarea and shows a visible retry message", () => {
  assert.match(pageSource, /notesRef\.current\?\.scrollIntoView/);
  assert.match(pageSource, /notesRef\.current\?\.focus/);
  assert.match(inputFormSource, /data-testid="edit-notes-message"/);
  assert.match(pageSource, /quoteContact/);
  assert.match(inputFormSource, /contactValue/);
  assert.match(inputFormSource, /onContactChange/);
  assert.match(pageSource, /setCustomerText\(savedNotes\)/);
});

test("initial desktop layout centers the Customer Notes card", () => {
  assert.match(pageSource, /app-grid-initial/);
  assert.match(cssSource, /\.app-grid-initial\s*\{/);
  assert.match(cssSource, /justify-content:\s*center/);
  assert.match(cssSource, /width:\s*min\(100%, 980px\)/);
});

test("workflow actions use customer-safe labels and clean estimate route", () => {
  assert.match(pageSource, /New Estimate/);
  assert.match(pageSource, /New Invoice/);
  assert.match(pageSource, /Recent Estimates/);
  assert.match(pageSource, /Record Manual Acceptance/);
  assert.doesNotMatch(pageSource, /Recent Activity/);
  assert.match(cssSource, /\.front-action-primary/);
  assert.match(cssSource, /min-height:\s*104px/);
  assert.match(pageSource, /front-future-card/);
  assert.match(pageSource, /To be added later/);
  assert.match(cssSource, /\.front-future-card\s*\{[^}]*margin-top:\s*2\.5rem/s);
  assert.match(pageSource, /front-action-row/);
  assert.match(cssSource, /\.front-action-row\s*\{[^}]*grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\)/s);
  assert.match(cssSource, /\.front-action-row \.front-action\s*\{[^}]*font-size:\s*15px[^}]*min-height:\s*58px/s);
  assert.match(cssSource, /\.front-action-secondary,[\s\S]*?background:\s*#dbeafe/);
  assert.match(cssSource, /\.front-action-invoice/);
  assert.match(cssSource, /\.front-action-recent/);
  assert.match(cssSource, /background:\s*#dbeafe/);
  assert.match(inputFormSource, /job-notes-emphasis">Paste or type everything here \(in ANY order\)/);
  assert.match(inputFormSource, /Customer name, phone\/email, address, work requested, options, prices, notes/);
  assert.match(inputFormSource, /Remove 2 maples, John Hudson, 22 Main street, Madison, 1234567890 wj234@gmail\.com option a remove only 1000, option b grind stumps and haul away 1900/);
  assert.match(inputFormSource, /Review Estimate/);
  assert.match(inputFormSource, /Clear/);
  assert.match(inputFormSource, /JOB_NOTES_TEXT_STYLE/);
  assert.match(inputFormSource, /JOB_NOTES_BUTTON_STYLE/);
  assert.match(inputFormSource, /job-notes-emphasis">Example:<\/strong>/);
  assert.match(cssSource, /\.text-inbox-title\s*\{[^}]*font-weight:\s*400/s);
  assert.match(cssSource, /\.job-notes-emphasis\s*\{[^}]*color:\s*#b91c1c[^}]*font-weight:\s*700/s);
  assert.match(cssSource, /\.job-notes-example-text\s*\{[^}]*font-weight:\s*400/s);
  assert.match(cssSource, /\.job-notes-textarea\s*\{[^}]*font-size:\s*17px[^}]*font-weight:\s*400/s);
  assert.doesNotMatch(inputFormSource, /Tree count/);
  assert.doesNotMatch(inputFormSource, /<option value="Auto">Auto<\/option>/);
  assert.doesNotMatch(inputFormSource, /<option value="Unknown">Unknown<\/option>/);
  assert.doesNotMatch(inputFormSource, /job-notes-card/);
  assert.doesNotMatch(inputFormSource, /Include<\/span> as much information as possible about the job, scope of work, and prices/);
  assert.match(inputFormSource, /btn-create-review/);
  assert.match(globalCssSource, /\.btn-create-review/);
  assert.match(globalCssSource, /\.banner/);
  assert.match(globalCssSource, /padding:\s*8px 14px/);
  assert.match(pdfGeneratorSource, /Inform Customer/);
  assert.match(pdfGeneratorSource, /Send SMS/);
  assert.match(pdfGeneratorSource, /Send Email/);
  assert.match(pdfGeneratorSource, /Download Customer Copy/);
  assert.match(pdfGeneratorSource, /Download Contractor Copy/);
  assert.match(pdfGeneratorSource, /Contractor copy includes internal warning notes from TD2/);
  assert.match(pdfGeneratorSource, /hasContractorWarnings/);
  assert.match(pdfGeneratorSource, /Copy Link to Estimate/);
  assert.match(pdfGeneratorSource, /Send Now/);
  assert.match(pdfGeneratorSource, /setActivePreview\(""\)/);
  assert.match(pdfGeneratorSource, /sendCustomerMessage/);
  assert.match(pdfGeneratorSource, /recipient:\s*"customer"/);
  assert.doesNotMatch(pdfGeneratorSource, /function sendMock/);
  assert.match(pdfGeneratorSource, /Copy Link to Completed Estimate/);
  assert.match(pdfGeneratorSource, /Back to Front Page/);
  assert.match(submissionButtonsSource, /Preview Email to Contractor/);
  assert.match(pdfGeneratorSource, /btn-neutral/);
  assert.match(pdfGeneratorSource, /btn-light-orange/);
  assert.match(pdfGeneratorSource, /btn-light-blue/);
  assert.match(pdfGeneratorSource, /btn-yellow/);
  assert.equal(existsSync("app/api/estimates/[documentId]/route.js"), true);
  assert.equal(existsSync("app/e/[estimateId]/page.js"), true);
  assert.equal(existsSync("app/e/[estimateId]/EstimateClient.jsx"), true);
});

test("review starts with status while confirm keeps final approval heading", () => {
  const reviewSource = readFileSync("app/components/JsonReview.jsx", "utf8");
  assert.match(pageSource, /stage === "review"/);
  assert.match(pageSource, /mode="review"/);
  assert.match(pageSource, /mode="confirm"/);
  assert.doesNotMatch(reviewSource, /AI Review/);
  assert.doesNotMatch(reviewSource, /Check details before confirming estimate/);
  assert.match(pageSource, /Shadow Version: deployed \+ more parsers\/normalizers/);
  assert.match(reviewSource, /review-card/);
  assert.match(reviewSource, /Confirm Estimate/);
  assert.match(reviewSource, /Estimate ready to be Confirmed/);
  assert.match(reviewSource, /needsSourceFactReview/);
  assert.match(reviewSource, /Review required before confirming Estimate/);
  assert.match(reviewSource, /showReadyStatus\s*=\s*canConfirmWithOverrides\s*&&\s*!needsSourceFactReview/);
  assert.doesNotMatch(reviewSource, /review-status-needs-info/);
  assert.match(cssSource, /\.review-status\s*\{[^}]*border-radius:\s*8px/s);
  assert.match(cssSource, /\.review-status\s*\{[^}]*margin:\s*10px auto 14px/s);
  assert.match(cssSource, /\.review-status\s*\{[^}]*font-size:\s*18px/s);
  assert.match(cssSource, /\.review-status\s*\{[^}]*min-height:\s*64px/s);
  assert.match(cssSource, /\.td2-required-info-card h3\s*\{[^}]*font-weight:\s*900/s);
  assert.match(reviewSource, /Job Notes/);
  assert.doesNotMatch(reviewSource, /Include:/);
  assert.doesNotMatch(reviewSource, /job-notes-example-text/);
  assert.match(reviewSource, /intake = \{\}/);
  assert.match(reviewSource, /intake\.address/);
  assert.match(reviewSource, /normalizeServiceAddress/);
  assert.match(pageSource, /intake=\{quoteContact\}/);
  assert.match(reviewSource, /buildCustomerJobSummary/);
  assert.match(reviewSource, /structuredJobSummary\s*\|\|\s*cleanJobNotesForReview/);
  assert.match(reviewSource, /Customer Options/);
  assert.match(reviewSource, /quote-option-card/);
  assert.match(reviewSource, /Option 1/);
  assert.match(reviewSource, /normalizeTreeServiceText/);
  assert.match(reviewSource, /orderJobWarningsLast/);
  assert.match(reviewSource, /Review these options/);
  assert.match(reviewSource, /Do not choose an option here/);
  assert.match(reviewSource, /Needs More Info/);
  assert.match(reviewSource, /warningItems/);
  assert.match(reviewSource, /internal-warning-list/);
  assert.doesNotMatch(reviewSource, /<h4>Notes<\/h4>/);
  assert.doesNotMatch(reviewSource, /Internal Warnings/);
  assert.match(reviewSource, /warning-card/);
  assert.match(reviewSource, /OverrideWarningCard/);
  assert.match(reviewSource, /ContactOverrideCheckbox/);
  assert.match(reviewSource, /AddressOverrideCheckbox/);
  assert.match(reviewSource, /inlineContactOverrideStatus/);
  assert.match(reviewSource, /inlineAddressOverrideStatus/);
  assert.match(reviewSource, /withoutInlineOverrideStatus/);
  assert.match(reviewSource, /contactOverrideStatus/);
  assert.match(reviewSource, /addressOverrideStatus/);
  assert.match(reviewSource, /lowerOverrideStatus/);
  assert.match(reviewSource, /Phone number is needed to SMS Estimate to Customer/);
  assert.match(reviewSource, /onKeyDown/);
  assert.match(reviewSource, /event\.key === "Enter"/);
  assert.match(reviewSource, /applyChange\(event\.currentTarget\.value\)/);
  assert.match(reviewSource, /helperPosition="label"/);
  assert.match(cssSource, /\.td2-inline-label-row\s*\{[^}]*display:\s*flex/s);
  assert.match(reviewSource, /Enter area code & phone #/);
  assert.match(reviewSource, /Enter Service Address or override-->/);
  assert.match(cssSource, /\.td2-phone-inline-field \.td2-inline-editor\s*\{[^}]*width:\s*30ch/s);
  assert.match(cssSource, /\.override-check-row\s*\{[^}]*grid-template-columns:\s*22px max-content/s);
  assert.match(cssSource, /\.override-check-row input\s*\{[^}]*height:\s*22px/s);
  assert.match(cssSource, /\.override-check-row input\s*\{[^}]*width:\s*22px/s);
  assert.match(cssSource, /\.override-check-row span\s*\{[^}]*white-space:\s*nowrap/s);
  assert.match(cssSource, /\.override-warning-item\s*\{[^}]*width:\s*fit-content/s);
  assert.match(cssSource, /\.td2-required-field-with-override\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\) auto/s);
  assert.match(cssSource, /\.td2-address-required-row\s*\{[^}]*gap:\s*4px/s);
  assert.match(cssSource, /\.td2-address-required-row\s*\{[^}]*grid-template-columns:\s*1fr/s);
  assert.match(reviewSource, /TreeCountResolutionCard/);
  assert.match(reviewSource, /Internal Warning/);
  assert.doesNotMatch(reviewSource, /Tree Dude Warning/);
  assert.match(reviewSource, /Tree Count Is Unclear/);
  assert.match(reviewSource, /Change Tree Count/);
  assert.match(reviewSource, /td2ManualTreeCountOverride/);
  assert.match(reviewSource, /3\+ trees/);
  assert.match(reviewSource, /Still unclear but OK to proceed/);
  assert.doesNotMatch(reviewSource, /Use this tree count/);
  assert.match(reviewSource, /Create Estimate without exact address/);
  assert.match(reviewSource, /Create Estimate without phone number/);
  assert.match(reviewSource, /Create Estimate without email/);
  assert.match(reviewSource, /Create Estimate without phone number or email/);
  assert.match(reviewSource, /Create Estimate with unclear work scope/);
  assert.match(reviewSource, /Prices are clear, but work scope needs Tree Dude approval/);
  assert.match(reviewSource, /isOverrideRelatedWarning/);
  assert.match(reviewSource, /override-check-row/);
  assert.match(reviewSource, /type="checkbox"/);
  assert.match(reviewSource, /Fix missing info before confirming estimate/);
  assert.match(reviewSource, /Edit TD1 Info\?\?/);
  assert.match(reviewSource, /customer-summary-card/);
  assert.match(reviewSource, /customer-info-grid/);
  assert.match(reviewSource, /normalizeEditedServiceAddress/);
  assert.match(reviewSource, /const rawJobAddress =/);
  assert.match(reviewSource, /const jobAddress = rawJobAddress \? normalizeEditedServiceAddress\(rawJobAddress\) \|\| rawJobAddress : "Address missing"/);
  assert.match(reviewSource, /splitServiceAddressDisplay/);
  assert.match(reviewSource, /LOCAL_INDIANA_TOWNS/);
  assert.match(reviewSource, /customerAddressLines/);
  assert.match(reviewSource, /customer-name-line/);
  assert.match(reviewSource, /customer-address-line/);
  assert.match(reviewSource, /customer-street-line/);
  assert.match(reviewSource, /customer-city-state-line/);
  assert.match(reviewSource, /customerPhoneValue/);
  assert.match(reviewSource, /customerPhoneAvailable/);
  assert.match(reviewSource, /const customerPhone = customerPhoneValue \|\| "Phone not available"/);
  assert.match(reviewSource, /customer-phone-available/);
  assert.match(reviewSource, /<span className="customer-street-line">\{customerAddressLines\.street\}<\/span>/);
  assert.match(reviewSource, /customerAddressLines\.cityState[\s\S]*,\s*\{customerAddressLines\.cityState\}/);
  assert.match(reviewSource, /<p>\{customerEmail\}<\/p>\s*<p className=\{customerPhoneAvailable/);
  assert.doesNotMatch(reviewSource, /customer-info-right/);
  assert.match(reviewSource, /td2-action-toolbar/);
  assert.match(cssSource, /\.td2-action-toolbar/);
  assert.match(cssSource, /\.warning-card/);
  assert.match(cssSource, /\.override-warning-card/);
  assert.match(cssSource, /\.override-warning-card h3\s*\{[^}]*font-weight:\s*900/s);
  assert.match(cssSource, /\.internal-warning-list\s*\{[^}]*margin:\s*0/s);
  assert.match(cssSource, /\.override-check-row/);
  assert.match(cssSource, /border:\s*2px solid #f97316/);
  assert.match(cssSource, /grid-template-columns:\s*max-content minmax\(0, 1fr\)/);
  assert.match(cssSource, /\.customer-summary-card/);
  assert.match(cssSource, /\.customer-info-grid/);
  assert.match(cssSource, /\.customer-name-line/);
  assert.match(cssSource, /\.customer-address-line/);
  assert.match(cssSource, /\.customer-street-line\s*\{[^}]*font-weight:\s*900/s);
  assert.match(cssSource, /\.customer-phone-available\s*\{[^}]*font-weight:\s*900/s);
  assert.doesNotMatch(cssSource, /\.customer-info-right/);
});

test("customer route requires compact e-signature consent and contractor panel does not sign for customer", () => {
  const consentText = /I agree to receive and sign this estimate electronically/;
  assert.match(customerRouteSource, consentText);
  assert.match(customerRouteSource, /checkboxAccepted/);
  assert.match(customerRouteSource, /buildCustomerJobSummary/);
  assert.match(customerRouteSource, /workDescription/);
  assert.doesNotMatch(pdfGeneratorSource, consentText);
  assert.doesNotMatch(pdfGeneratorSource, /checkboxAccepted/);
  assert.doesNotMatch(pdfGeneratorSource, /onSelectOption/);
});

test("customer-facing estimate documents use cleaned job notes without internal evidence fields", () => {
  const customerDocumentSource = readFileSync("lib/customerDocument.js", "utf8");
  const pdfRouteSource = readFileSync("app/api/pdf/route.js", "utf8");
  assert.match(customerDocumentSource, /buildCustomerJobSummary/);
  assert.match(customerDocumentSource, /workDescription/);
  assert.match(customerDocumentSource, /renderTreeDudeDocument/);
  assert.match(customerDocumentSource, /Contractor Copy/);
  assert.match(customerDocumentSource, /These warnings are for the contractor copy only/);
  assert.match(customerDocumentSource, /Preview Email to Contractor/);
  assert.match(pdfRouteSource, /renderCustomerDocument\(alphaJson, \{ mobile: false \}\)/);
  assert.match(pdfRouteSource, /renderCustomerDocument\(alphaJson, \{ mobile: true \}\)/);
  assert.match(pdfRouteSource, /renderTreeDudeDocument/);
  assert.match(pdfRouteSource, /contractorWarnings\.length > 0/);
  assert.match(pdfRouteSource, /if \(treeDude\) recordPayload\.pdf_url_tree_dude/);
  assert.match(pdfRouteSource, /override_warnings/);
  assert.match(pdfRouteSource, /contractor_warnings/);
  assert.doesNotMatch(customerRouteSource, /field_evidence/);
  assert.doesNotMatch(customerRouteSource, /uncertainties/);
  assert.doesNotMatch(customerDocumentSource, /field_evidence/);
  assert.doesNotMatch(customerDocumentSource, /uncertainties/);
});

test("review overrides are narrow and recorded separately from normal validation", () => {
  const pageSource = readFileSync("app/page.js", "utf8");
  const pdfRouteSource = readFileSync("app/api/pdf/route.js", "utf8");
  assert.match(pageSource, /reviewOverrides/);
  assert.match(pageSource, /onReviewOverridesChange/);
  assert.match(pageSource, /normalizeEditedServiceAddress/);
  assert.match(pageSource, /const normalizedAddress = normalizeEditedServiceAddress\(nextValue\) \|\| nextValue/);
  assert.match(pageSource, /const REQUIRED_PHONE_DIGITS = 10/);
  assert.match(pageSource, /phoneDigitCount\(nextValue\) !== REQUIRED_PHONE_DIGITS/);
  assert.match(pageSource, /PHONE_DIGIT_WARNING/);
  assert.match(readFileSync("app/components/JsonReview.jsx", "utf8"), /Phone number must be \$\{REQUIRED_PHONE_DIGITS\} digits including area code/);
  assert.match(readFileSync("app/components/JsonReview.jsx", "utf8"), /replace\(\/\\D\/g, ""\)\.length/);
  assert.match(readFileSync("app/components/JsonReview.jsx", "utf8"), /onDraftChange\?\.\(event\.target\.value\)/);
  assert.match(readFileSync("app/components/JsonReview.jsx", "utf8"), /handlePhoneDraftChange/);
  assert.match(readFileSync("app/components/JsonReview.jsx", "utf8"), /phoneDigitCount\(value\) === REQUIRED_PHONE_DIGITS/);
  assert.match(readFileSync("app/components/JsonReview.jsx", "utf8"), /const phoneOverrideAccepted = Boolean\(reviewOverrides\?\.missingPhone \|\| reviewOverrides\?\.missingContact\)/);
  assert.match(readFileSync("app/components/JsonReview.jsx", "utf8"), /if \(!needsPhone \|\| phoneOverrideAccepted\) setPhoneWarning\(""\)/);
  assert.match(readFileSync("app/components/JsonReview.jsx", "utf8"), /error=\{phoneOverrideAccepted \? "" : phoneWarning\}/);
  assert.match(readFileSync("app/components/JsonReview.jsx", "utf8"), /td2-inline-field-error/);
  assert.match(pageSource, /postJson\("\/api\/pdf", \{ alphaJson, reviewOverrides \}\)/);
  assert.match(reviewOverridesSource, /Missing service address/);
  assert.match(reviewOverridesSource, /Missing customer phone or email/);
  assert.match(reviewOverridesSource, /Service address is missing, but was OK'd when the estimate was created/);
  assert.match(reviewOverridesSource, /Service address is not clear, but was OK'd when the estimate was created/);
  assert.match(reviewOverridesSource, /Customer phone number is missing, but email is given/);
  assert.match(reviewOverridesSource, /Customer email is missing, but phone number is given/);
  assert.match(reviewOverridesSource, /Work scope is unclear, but the displayed price was OK'd/);
  assert.match(reviewOverridesSource, /Phone is the preferred contact method/);
  assert.match(pdfRouteSource, /getBlockingOverrideStatus/);
  assert.match(pdfRouteSource, /canGenerateWithOverrides/);
  assert.match(pdfRouteSource, /structuralBlockingErrors/);
  assert.match(pdfRouteSource, /Final customer option structure must be fixed/);
  assert.match(readFileSync("app/components/JsonReview.jsx", "utf8"), /const canConfirmWithOverrides = overrideStatus\.canProceed/);
  assert.match(pdfRouteSource, /remainingBlockingErrors/);
});

test("TD2 can edit highlighted option descriptions in place", () => {
  const pageSource = readFileSync("app/page.js", "utf8");
  const reviewSource = readFileSync("app/components/JsonReview.jsx", "utf8");
  const cssSource = readFileSync("app/styles/globals.css", "utf8");

  assert.match(pageSource, /applyOptionDescriptionEdit/);
  assert.match(pageSource, /normalizeTreeServiceText\(description\)/);
  assert.match(pageSource, /optionTitleIsGeneric/);
  assert.match(pageSource, /titleFromConfirmedScope/);
  assert.match(pageSource, /updateGenericTitle/);
  assert.match(pageSource, /onOptionDescriptionChange=\{applyOptionDescriptionEdit\}/);
  assert.match(reviewSource, /function optionRenderKey/);
  assert.match(reviewSource, /key=\{optionRenderKey\(option, index\)\}/);
  assert.doesNotMatch(reviewSource, /key=\{option\.label \|\| index\}/);
  assert.match(reviewSource, /optionNeedsDescriptionReview/);
  assert.match(reviewSource, /!isFinalConfirm && optionNeedsDescriptionReview\(option\).*quote-option-card-warning/);
  assert.match(reviewSource, /source_fact_clarification/);
  assert.match(reviewSource, /OptionDescriptionEditor/);
  assert.match(reviewSource, /Write the confirmed work scope for this option/);
  assert.match(reviewSource, /This replaces the customer-facing option description/);
  assert.match(reviewSource, /This replaces the customer-facing option description[\s\S]*?<textarea/);
  assert.match(reviewSource, /OptionPriceEditor/);
  assert.match(reviewSource, /RequiredInfoEditor/);
  assert.match(reviewSource, /More info is needed to complete Estimate/);
  assert.match(pageSource, /applyCustomerFieldEdit/);
  assert.match(pageSource, /applyOptionPriceEdit/);
  assert.match(pageSource, /initial_display: items\[optionIndex\]\.price\?\.initial_display \|\| items\[optionIndex\]\.price\?\.display \|\| ""/);
  assert.match(pageSource, /edited_by_td: true/);
  assert.match(pageSource, /applyAddOption/);
  assert.match(reviewSource, /spellCheck="true"/);
  assert.match(reviewSource, /const initialPrice = option\.price\?\.initial_display \|\| ""/);
  assert.match(reviewSource, /option-price-label-changed/);
  assert.match(reviewSource, /Price was changed or added/);
  assert.match(reviewSource, /!isFinalConfirm && onOptionPriceChange \?/);
  assert.doesNotMatch(reviewSource, /!isFinalConfirm && optionNeedsPriceReview\(option\) && onOptionPriceChange/);
  assert.match(cssSource, /\.quote-option-card-warning/);
  assert.match(cssSource, /border:\s*4px solid #b91c1c/);
  assert.match(cssSource, /\.option-description-editor-warning/);
  assert.match(cssSource, /\.option-description-clarifier\s*\{[^}]*gap:\s*2px/s);
  assert.match(cssSource, /\.option-description-clarifier \.td2-inline-help\s*\{[^}]*font-size:\s*inherit[^}]*font-weight:\s*400/s);
  assert.match(cssSource, /\.option-price-label\s*\{[^}]*color:\s*var\(--ink\)/s);
  assert.match(cssSource, /\.option-price-label\s*\{[^}]*font-size:\s*16px/s);
  assert.match(cssSource, /\.option-price-label\s*\{[^}]*font-weight:\s*700/s);
  assert.match(cssSource, /\.option-price-label\s*\{[^}]*text-transform:\s*uppercase/s);
  assert.match(cssSource, /\.option-price-input\s*\{[^}]*font-size:\s*16px/s);
  assert.match(cssSource, /\.option-price-input\s*\{[^}]*text-align:\s*left/s);
  assert.match(cssSource, /\.option-price-input\s*\{[^}]*width:\s*10ch/s);
  assert.match(cssSource, /\.quote-option-heading > strong\s*\{[^}]*text-transform:\s*uppercase/s);
  assert.match(cssSource, /\.option-price-change-note\s*\{[^}]*text-transform:\s*none/s);
});

test("manual acceptance foundation exists without multi-company scope", () => {
  assert.equal(existsSync("app/api/manual-acceptance/route.js"), true);
  assert.match(pdfGeneratorSource, /Record Manual Acceptance/);
  assert.match(pdfGeneratorSource, /Acceptance has been saved/);
  assert.match(pdfGeneratorSource, /Download Saved Estimate/);
  assert.doesNotMatch(pdfGeneratorSource, /Beta Tree/i);
});

test("OpenAI route can use reasoning effort without affecting non-reasoning models", () => {
  const envExampleSource = readFileSync(".env.example", "utf8");
  assert.match(openaiRouteSource, /OPENAI_REASONING_EFFORT/);
  assert.match(openaiRouteSource, /reasoning_effort/);
  assert.match(openaiRouteSource, /gpt-5/);
  assert.match(openaiRouteSource, /gpt-4\.1-nano/);
  assert.match(envExampleSource, /OPENAI_REASONING_EFFORT=/);
});

test("OpenAI route logs production case metrics without raw customer text", () => {
  assert.match(openaiRouteSource, /openai_case_result/);
  assert.match(openaiRouteSource, /case_id/);
  assert.match(openaiRouteSource, /model/);
  assert.match(openaiRouteSource, /reasoning_effort/);
  assert.match(openaiRouteSource, /input_tokens/);
  assert.match(openaiRouteSource, /output_tokens/);
  assert.match(openaiRouteSource, /total_tokens/);
  assert.match(openaiRouteSource, /parse_block_outcome/);
  assert.match(openaiRouteSource, /error_message/);
  assert.match(openaiRouteSource, /validateAlphaJson/);
  assert.doesNotMatch(openaiRouteSource, /customerText,\s*$/m);
});

test("OpenAI prompt and route keep model output at extraction-draft boundary", () => {
  assert.match(openaiPromptSource, /draft_version/);
  assert.match(openaiPromptSource, /Do not create final AlphaJSON/);
  assert.match(openaiPromptSource, /Do not decide whether PDF generation is allowed/);
  assert.match(openaiPromptSource, /Do not sort or relabel options/);
  assert.doesNotMatch(openaiPromptSource, /alphaJson must be compatible/i);
  assert.doesNotMatch(openaiPromptSource, /Set validation\.can_generate_pdf/i);
  assert.match(openaiRouteSource, /parseOpenAiDraft/);
  assert.match(openaiRouteSource, /openAiDraftToNormalizerInput/);
  assert.match(openaiRouteSource, /OPENAI_DRAFT_RESPONSE_FORMAT/);
  assert.match(openaiRouteSource, /ENABLE_TD1_PRE_NORMALIZERS/);
  assert.match(openaiRouteSource, /td1PreNormalizersEnabled/);
  assert.match(openaiRouteSource, /preNormalizersEnabled\s*\?\s*textCleanupNormalizer\(customerText\)\s*:\s*null/);
  assert.match(openaiRouteSource, /preNormalizersEnabled[\s\S]*normalizeContactFields\(\{\s*rawText:\s*customerText,\s*intake\s*\}\)/);
  assert.match(openaiRouteSource, /protectedContactSpans/);
  assert.match(openaiRouteSource, /buildOptionPriceCandidateView\(\s*customerText,\s*protectedContactSpans\(contactNormalizationResult\),\s*\{/);
  assert.match(openaiRouteSource, /cleanedText:\s*literalTextCleanupResult\?\.cleanedText/);
  assert.match(openaiRouteSource, /buildPreNormalizerParserInput\(\{/);
  assert.match(openaiRouteSource, /contactNormalizationResult,\s*optionPriceCandidateView/s);
  assert.match(openaiRouteSource, /:\s*customerText/);
  assert.match(openaiRouteSource, /content:\s*parserCustomerText/);
  assert.match(openaiRouteSource, /textCleanupResult/);
  assert.match(openaiRouteSource, /contactNormalizationResult/);
  assert.match(openaiRouteSource, /optionPriceCandidateView/);
  assert.match(openaiRouteSource, /applyContactNormalizationOverlay/);
  assert.doesNotMatch(openaiRouteSource, /json_object/);
  assert.match(openaiRouteSource, /applyContactNormalizationOverlay\(\s*normalizeToAlphaJsonV14\(normalizerInput,\s*customerText,\s*intake\),\s*contactNormalizationResult/s);
  assert.match(openaiRouteSource, /buildDebugPipelinePayload/);
  assert.match(debugPipelineSource, /structured_follow_ups/);
  assert.match(debugPipelineSource, /td1TextCleanup/);
  assert.match(debugPipelineSource, /td1ContactNormalization/);
  assert.match(debugPipelineSource, /td1OptionPriceCandidateView/);
  assert.match(debugPipelineSource, /sourceFinalFactCoverage/);
  assert.match(jsonReviewSource, /Source-Final Coverage/);
});
