import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { existsSync } from "node:fs";

const pageSource = readFileSync("app/page.js", "utf8");
const inputFormSource = readFileSync("app/components/InputForm.jsx", "utf8");
const pdfGeneratorSource = readFileSync("app/components/PdfGenerator.jsx", "utf8");
const submissionButtonsSource = readFileSync("app/components/SubmissionButtons.jsx", "utf8");
const cssSource = readFileSync("app/styles/globals.css", "utf8");
const globalCssSource = readFileSync("styles-globals.css", "utf8");
const customerRouteSource = readFileSync("app/e/[estimateId]/EstimateClient.jsx", "utf8");
const openaiRouteSource = readFileSync("app/api/openai/route.js", "utf8");
const openaiPromptSource = readFileSync("lib/openaiPrompt.js", "utf8");
const debugPipelineSource = readFileSync("lib/debugPipeline.js", "utf8");
const reviewOverridesSource = readFileSync("lib/reviewOverrides.js", "utf8");

test("normal UI does not render raw AlphaJSON debug panel", () => {
  assert.doesNotMatch(pageSource, /<h2>AlphaJSON<\/h2>/);
  assert.doesNotMatch(pageSource, /JSON\.stringify\(alphaJson/);
});

test("Edit Notes focuses the textarea and shows a visible retry message", () => {
  assert.match(pageSource, /notesRef\.current\?\.scrollIntoView/);
  assert.match(pageSource, /notesRef\.current\?\.focus/);
  assert.match(inputFormSource, /data-testid="edit-notes-message"/);
  assert.match(pageSource, /quoteContact/);
  assert.match(inputFormSource, /contactValue/);
  assert.match(inputFormSource, /onContactChange/);
  assert.match(pageSource, /setCustomerText\(savedNotes\)/);
});

test("initial desktop layout centers the Customer Notes card", () => {
  assert.match(pageSource, /app-grid-initial/);
  assert.match(cssSource, /\.app-grid-initial\s*\{/);
  assert.match(cssSource, /justify-content:\s*center/);
  assert.match(cssSource, /width:\s*min\(100%, 980px\)/);
});

test("workflow actions use customer-safe labels and clean estimate route", () => {
  assert.match(pageSource, /New Estimate/);
  assert.match(pageSource, /New Invoice/);
  assert.match(pageSource, /Recent Estimates/);
  assert.match(pageSource, /Record Manual Acceptance/);
  assert.doesNotMatch(pageSource, /Recent Activity/);
  assert.match(cssSource, /\.front-action-primary/);
  assert.match(cssSource, /min-height:\s*104px/);
  assert.match(cssSource, /\.front-action-invoice/);
  assert.match(cssSource, /\.front-action-recent/);
  assert.match(cssSource, /background:\s*#dbeafe/);
  assert.match(inputFormSource, /Paste or type everything here \(in ANY order\)/);
  assert.match(inputFormSource, /Add customer info, number of trees, prices and service for each option/);
  assert.match(inputFormSource, /Remove 2 maples for John, 22 Main street, Madison/);
  assert.match(inputFormSource, /Review Estimate/);
  assert.match(inputFormSource, /Clear/);
  assert.doesNotMatch(inputFormSource, /Tree count/);
  assert.doesNotMatch(inputFormSource, /<option value="Auto">Auto<\/option>/);
  assert.doesNotMatch(inputFormSource, /<option value="Unknown">Unknown<\/option>/);
  assert.doesNotMatch(inputFormSource, /job-notes-card/);
  assert.doesNotMatch(inputFormSource, /Include<\/span> as much information as possible about the job, scope of work, and prices/);
  assert.match(inputFormSource, /btn-create-review/);
  assert.match(globalCssSource, /\.btn-create-review/);
  assert.match(globalCssSource, /\.banner/);
  assert.match(globalCssSource, /padding:\s*8px 14px/);
  assert.match(pdfGeneratorSource, /Inform Customer/);
  assert.match(pdfGeneratorSource, /Send SMS/);
  assert.match(pdfGeneratorSource, /Send Email/);
  assert.match(pdfGeneratorSource, /Download Customer Copy/);
  assert.match(pdfGeneratorSource, /Download Contractor Copy/);
  assert.match(pdfGeneratorSource, /Contractor copy includes internal warning notes from TD2/);
  assert.match(pdfGeneratorSource, /hasContractorWarnings/);
  assert.match(pdfGeneratorSource, /Copy Link to Estimate/);
  assert.match(pdfGeneratorSource, /Send Now/);
  assert.match(pdfGeneratorSource, /setActivePreview\(""\)/);
  assert.match(pdfGeneratorSource, /sendCustomerMessage/);
  assert.match(pdfGeneratorSource, /recipient:\s*"customer"/);
  assert.doesNotMatch(pdfGeneratorSource, /function sendMock/);
  assert.match(pdfGeneratorSource, /Copy Link to Completed Estimate/);
  assert.match(pdfGeneratorSource, /Back to Front Page/);
  assert.match(submissionButtonsSource, /Preview Email to Contractor/);
  assert.match(pdfGeneratorSource, /btn-neutral/);
  assert.match(pdfGeneratorSource, /btn-light-orange/);
  assert.match(pdfGeneratorSource, /btn-light-blue/);
  assert.match(pdfGeneratorSource, /btn-yellow/);
  assert.equal(existsSync("app/api/estimates/[documentId]/route.js"), true);
  assert.equal(existsSync("app/e/[estimateId]/page.js"), true);
  assert.equal(existsSync("app/e/[estimateId]/EstimateClient.jsx"), true);
});

test("review and confirm screens separate AI review from final quote approval", () => {
  const reviewSource = readFileSync("app/components/JsonReview.jsx", "utf8");
  assert.match(pageSource, /stage === "review"/);
  assert.match(pageSource, /mode="review"/);
  assert.match(pageSource, /mode="confirm"/);
  assert.match(reviewSource, /AI Review/);
  assert.match(reviewSource, /Check details before confirming quote/);
  assert.match(reviewSource, /Review ready/);
  assert.doesNotMatch(reviewSource, /review-status-needs-info/);
  assert.match(cssSource, /\.td2-required-info-card h3\s*\{[^}]*font-weight:\s*900/s);
  assert.match(reviewSource, /Job Notes/);
  assert.doesNotMatch(reviewSource, /Include:/);
  assert.doesNotMatch(reviewSource, /job-notes-example-text/);
  assert.match(reviewSource, /intake = \{\}/);
  assert.match(reviewSource, /intake\.address/);
  assert.match(reviewSource, /normalizeServiceAddress/);
  assert.match(pageSource, /intake=\{quoteContact\}/);
  assert.match(reviewSource, /buildCustomerJobSummary/);
  assert.match(reviewSource, /structuredJobSummary\s*\|\|\s*cleanJobNotesForReview/);
  assert.match(reviewSource, /Quote Options/);
  assert.match(reviewSource, /Customer Options/);
  assert.match(reviewSource, /quote-option-card/);
  assert.match(reviewSource, /Option 1/);
  assert.match(reviewSource, /normalizeTreeServiceText/);
  assert.match(reviewSource, /orderJobWarningsLast/);
  assert.match(reviewSource, /Review these options/);
  assert.match(reviewSource, /Do not choose an option here/);
  assert.match(reviewSource, /Needs More Info/);
  assert.match(reviewSource, /warningItems/);
  assert.match(reviewSource, /Notes/);
  assert.doesNotMatch(reviewSource, /Internal Warnings/);
  assert.match(reviewSource, /warning-card/);
  assert.match(reviewSource, /OverrideWarningCard/);
  assert.match(reviewSource, /ContactOverrideCheckbox/);
  assert.match(reviewSource, /contactOnlyOverrideStatus/);
  assert.match(reviewSource, /withoutContactOverrideStatus/);
  assert.match(reviewSource, /contactOverrideStatus/);
  assert.match(reviewSource, /lowerOverrideStatus/);
  assert.match(reviewSource, /TreeCountResolutionCard/);
  assert.match(reviewSource, /Internal Warning/);
  assert.doesNotMatch(reviewSource, /Tree Dude Warning/);
  assert.match(reviewSource, /Tree Count Is Unclear/);
  assert.match(reviewSource, /3\+ trees/);
  assert.match(reviewSource, /Still unclear but OK to proceed/);
  assert.match(reviewSource, /Use this tree count/);
  assert.match(reviewSource, /Create Estimate without exact address/);
  assert.match(reviewSource, /Create Estimate without phone number/);
  assert.match(reviewSource, /Create Estimate without email/);
  assert.match(reviewSource, /Create Estimate without phone number or email/);
  assert.match(reviewSource, /Create Estimate with unclear work scope/);
  assert.match(reviewSource, /Prices are clear, but work scope needs Tree Dude approval/);
  assert.match(reviewSource, /isOverrideRelatedWarning/);
  assert.match(reviewSource, /override-check-row/);
  assert.match(reviewSource, /type="checkbox"/);
  assert.match(reviewSource, /Fix missing info before confirming quote/);
  assert.match(reviewSource, /Edit Info/);
  assert.match(reviewSource, /customer-summary-card/);
  assert.match(reviewSource, /customer-info-grid/);
  assert.match(reviewSource, /customer-info-right/);
  assert.match(reviewSource, /td2-action-toolbar/);
  assert.match(cssSource, /\.td2-action-toolbar/);
  assert.match(cssSource, /\.warning-card/);
  assert.match(cssSource, /\.override-warning-card/);
  assert.match(cssSource, /\.override-check-row/);
  assert.match(cssSource, /border:\s*2px solid #f97316/);
  assert.match(cssSource, /grid-template-columns:\s*max-content minmax\(0, 1fr\)/);
  assert.match(cssSource, /\.customer-summary-card/);
  assert.match(cssSource, /\.customer-info-grid/);
});

test("customer route requires compact e-signature consent and contractor panel does not sign for customer", () => {
  const consentText = /I agree to receive and sign this estimate electronically/;
  assert.match(customerRouteSource, consentText);
  assert.match(customerRouteSource, /checkboxAccepted/);
  assert.match(customerRouteSource, /buildCustomerJobSummary/);
  assert.match(customerRouteSource, /workDescription/);
  assert.doesNotMatch(pdfGeneratorSource, consentText);
  assert.doesNotMatch(pdfGeneratorSource, /checkboxAccepted/);
  assert.doesNotMatch(pdfGeneratorSource, /onSelectOption/);
});

test("customer-facing estimate documents use cleaned job notes without internal evidence fields", () => {
  const customerDocumentSource = readFileSync("lib/customerDocument.js", "utf8");
  const pdfRouteSource = readFileSync("app/api/pdf/route.js", "utf8");
  assert.match(customerDocumentSource, /buildCustomerJobSummary/);
  assert.match(customerDocumentSource, /workDescription/);
  assert.match(customerDocumentSource, /renderTreeDudeDocument/);
  assert.match(customerDocumentSource, /Contractor Copy/);
  assert.match(customerDocumentSource, /These warnings are for the contractor copy only/);
  assert.match(customerDocumentSource, /Preview Email to Contractor/);
  assert.match(pdfRouteSource, /renderCustomerDocument\(alphaJson, \{ mobile: false \}\)/);
  assert.match(pdfRouteSource, /renderCustomerDocument\(alphaJson, \{ mobile: true \}\)/);
  assert.match(pdfRouteSource, /renderTreeDudeDocument/);
  assert.match(pdfRouteSource, /contractorWarnings\.length > 0/);
  assert.match(pdfRouteSource, /if \(treeDude\) recordPayload\.pdf_url_tree_dude/);
  assert.match(pdfRouteSource, /override_warnings/);
  assert.match(pdfRouteSource, /contractor_warnings/);
  assert.doesNotMatch(customerRouteSource, /field_evidence/);
  assert.doesNotMatch(customerRouteSource, /uncertainties/);
  assert.doesNotMatch(customerDocumentSource, /field_evidence/);
  assert.doesNotMatch(customerDocumentSource, /uncertainties/);
});

test("review overrides are narrow and recorded separately from normal validation", () => {
  const pageSource = readFileSync("app/page.js", "utf8");
  const pdfRouteSource = readFileSync("app/api/pdf/route.js", "utf8");
  assert.match(pageSource, /reviewOverrides/);
  assert.match(pageSource, /onReviewOverridesChange/);
  assert.match(pageSource, /postJson\("\/api\/pdf", \{ alphaJson, reviewOverrides \}\)/);
  assert.match(reviewOverridesSource, /Missing service address/);
  assert.match(reviewOverridesSource, /Missing customer phone or email/);
  assert.match(reviewOverridesSource, /Service address is missing, but was OK'd when the estimate was created/);
  assert.match(reviewOverridesSource, /Service address is not clear, but was OK'd when the estimate was created/);
  assert.match(reviewOverridesSource, /Customer phone number is missing, but email is given/);
  assert.match(reviewOverridesSource, /Customer email is missing, but phone number is given/);
  assert.match(reviewOverridesSource, /Work scope is unclear, but the displayed price was OK'd/);
  assert.match(reviewOverridesSource, /Phone is the preferred contact method/);
  assert.match(pdfRouteSource, /getBlockingOverrideStatus/);
  assert.match(pdfRouteSource, /canGenerateWithOverrides/);
  assert.match(readFileSync("app/components/JsonReview.jsx", "utf8"), /const canConfirmWithOverrides = overrideStatus\.canProceed/);
  assert.match(pdfRouteSource, /remainingBlockingErrors/);
});

test("TD2 can edit highlighted option descriptions in place", () => {
  const pageSource = readFileSync("app/page.js", "utf8");
  const reviewSource = readFileSync("app/components/JsonReview.jsx", "utf8");
  const cssSource = readFileSync("app/styles/globals.css", "utf8");

  assert.match(pageSource, /applyOptionDescriptionEdit/);
  assert.match(pageSource, /onOptionDescriptionChange=\{applyOptionDescriptionEdit\}/);
  assert.match(reviewSource, /optionNeedsDescriptionReview/);
  assert.match(reviewSource, /OptionDescriptionEditor/);
  assert.match(reviewSource, /OptionPriceEditor/);
  assert.match(reviewSource, /RequiredInfoEditor/);
  assert.match(reviewSource, /More info is needed to complete Estimate/);
  assert.match(pageSource, /applyCustomerFieldEdit/);
  assert.match(pageSource, /applyOptionPriceEdit/);
  assert.match(pageSource, /applyAddOption/);
  assert.match(reviewSource, /spellCheck="true"/);
  assert.match(cssSource, /\.quote-option-card-warning/);
  assert.match(cssSource, /border:\s*4px solid #b91c1c/);
  assert.match(cssSource, /\.option-description-editor-warning/);
});

test("manual acceptance foundation exists without multi-company scope", () => {
  assert.equal(existsSync("app/api/manual-acceptance/route.js"), true);
  assert.match(pdfGeneratorSource, /Record Manual Acceptance/);
  assert.match(pdfGeneratorSource, /Acceptance has been saved/);
  assert.match(pdfGeneratorSource, /Download Saved Estimate/);
  assert.doesNotMatch(pdfGeneratorSource, /Beta Tree/i);
});

test("OpenAI route can use reasoning effort without affecting non-reasoning models", () => {
  const envExampleSource = readFileSync(".env.example", "utf8");
  assert.match(openaiRouteSource, /OPENAI_REASONING_EFFORT/);
  assert.match(openaiRouteSource, /reasoning_effort/);
  assert.match(openaiRouteSource, /gpt-5/);
  assert.match(openaiRouteSource, /gpt-4\.1-nano/);
  assert.match(envExampleSource, /OPENAI_REASONING_EFFORT=/);
});

test("OpenAI route logs production case metrics without raw customer text", () => {
  assert.match(openaiRouteSource, /openai_case_result/);
  assert.match(openaiRouteSource, /case_id/);
  assert.match(openaiRouteSource, /model/);
  assert.match(openaiRouteSource, /reasoning_effort/);
  assert.match(openaiRouteSource, /input_tokens/);
  assert.match(openaiRouteSource, /output_tokens/);
  assert.match(openaiRouteSource, /total_tokens/);
  assert.match(openaiRouteSource, /parse_block_outcome/);
  assert.match(openaiRouteSource, /error_message/);
  assert.match(openaiRouteSource, /validateAlphaJson/);
  assert.doesNotMatch(openaiRouteSource, /customerText,\s*$/m);
});

test("OpenAI prompt and route keep model output at extraction-draft boundary", () => {
  assert.match(openaiPromptSource, /draft_version/);
  assert.match(openaiPromptSource, /Do not create final AlphaJSON/);
  assert.match(openaiPromptSource, /Do not decide whether PDF generation is allowed/);
  assert.match(openaiPromptSource, /Do not sort or relabel options/);
  assert.doesNotMatch(openaiPromptSource, /alphaJson must be compatible/i);
  assert.doesNotMatch(openaiPromptSource, /Set validation\.can_generate_pdf/i);
  assert.match(openaiRouteSource, /parseOpenAiDraft/);
  assert.match(openaiRouteSource, /openAiDraftToNormalizerInput/);
  assert.match(openaiRouteSource, /OPENAI_DRAFT_RESPONSE_FORMAT/);
  assert.match(openaiRouteSource, /ENABLE_TD1_PRE_NORMALIZERS/);
  assert.match(openaiRouteSource, /td1PreNormalizersEnabled/);
  assert.match(openaiRouteSource, /preNormalizersEnabled\s*\?\s*textCleanupNormalizer\(customerText\)\s*:\s*null/);
  assert.match(openaiRouteSource, /preNormalizersEnabled[\s\S]*normalizeContactFields\(\{\s*rawText:\s*customerText,\s*intake\s*\}\)/);
  assert.match(openaiRouteSource, /protectedContactSpans/);
  assert.match(openaiRouteSource, /buildOptionPriceCandidateView\(\s*customerText,\s*protectedContactSpans\(contactNormalizationResult\),\s*\{/);
  assert.match(openaiRouteSource, /cleanedText:\s*literalTextCleanupResult\?\.cleanedText/);
  assert.match(openaiRouteSource, /buildPreNormalizerParserInput\(\{/);
  assert.match(openaiRouteSource, /contactNormalizationResult,\s*optionPriceCandidateView/s);
  assert.match(openaiRouteSource, /:\s*customerText/);
  assert.match(openaiRouteSource, /content:\s*parserCustomerText/);
  assert.match(openaiRouteSource, /textCleanupResult/);
  assert.match(openaiRouteSource, /contactNormalizationResult/);
  assert.match(openaiRouteSource, /optionPriceCandidateView/);
  assert.match(openaiRouteSource, /applyContactNormalizationOverlay/);
  assert.doesNotMatch(openaiRouteSource, /json_object/);
  assert.match(openaiRouteSource, /applyContactNormalizationOverlay\(\s*normalizeToAlphaJsonV14\(normalizerInput,\s*customerText,\s*intake\),\s*contactNormalizationResult/s);
  assert.match(openaiRouteSource, /buildDebugPipelinePayload/);
  assert.match(debugPipelineSource, /structured_follow_ups/);
  assert.match(debugPipelineSource, /td1TextCleanup/);
  assert.match(debugPipelineSource, /td1ContactNormalization/);
  assert.match(debugPipelineSource, /td1OptionPriceCandidateView/);
});
